### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by brenowschneider** [prodest/organograma-web-api#14]
Objetivos

- [ ] #13  -  Criação do ambiente de desenvolvimento (e publicação do sistema)
- [ ] #9  -  EU027 - Consulta de Muncípios
- [ ] #15  - Revisão da tabela de municípios no banco de dados

Métricas e Critérios:
A Sprint vai durar 1 semana e será considerada um sucesso caso:

- Um usuário, acessando a Web API do Organograma no ambiente de desenvolvimento, consiga consultar a lista de municípios.
